// Copyright 2023–2025 Skip
// SPDX-License-Identifier: LGPL-3.0-only WITH LGPL-3.0-linking-exception
import Foundation
import OSLog
import XCTest

@available(macOS 13, iOS 16, watchOS 10, tvOS 16, *)
final class BundleTests: XCTestCase {
    let logger: Logger = Logger(subsystem: "test", category: "BundleTests")

    func testBundle() throws {
        // Swift will be: Contents/Resources/ -- file:///~/Library/Developer/Xcode/DerivedData/DemoApp-ABCDEF/Build/Products/Debug/SkipFoundationTests.xctest/Contents/Resources/Skip_SkipFoundationTests.bundle/
        // Kotlin will be: file:///~/Library/Developer/Xcode/DerivedData/DemoApp-ABCDEF/Build/Products/Debug/SkipFoundationTests.xctest/Contents/Resources/skip-foundation_SkipFoundationTests.bundle/Contents/Resources/textasset.txt

        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "textasset", withExtension: "txt", subdirectory: nil, localization: nil))
        logger.info("resourceURL: \(resourceURL.absoluteString)")
        let str = try String(contentsOf: resourceURL)
        XCTAssertEqual("Some text\n", str)
    }

    // MARK: - Process mode resources (existing behavior)

    func testProcessedResourceTextAsset() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "textasset", withExtension: "txt"))
        let str = try String(contentsOf: resourceURL)
        XCTAssertEqual("Some text\n", str)
    }

    func testProcessedResourcePlist() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "SampleInfo", withExtension: "plist"))
        let data = try Data(contentsOf: resourceURL)
        XCTAssertTrue(data.count > 0, "SampleInfo.plist should not be empty")
    }

    // MARK: - Copy mode resources (preserving hierarchy)

    func testCopyResourceRootFile() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "root-file", withExtension: "txt", subdirectory: "ResourcesCopy"))
        let str = try String(contentsOf: resourceURL)
        XCTAssertEqual("Root file content\n", str)
    }

    func testCopyResourceSubdirectoryFile() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "mid-file", withExtension: "txt", subdirectory: "ResourcesCopy/subdir"))
        let str = try String(contentsOf: resourceURL)
        XCTAssertEqual("Mid-level file content\n", str)
    }

    func testCopyResourceNestedFile() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "deep-file", withExtension: "txt", subdirectory: "ResourcesCopy/subdir/nested"))
        let str = try String(contentsOf: resourceURL)
        XCTAssertEqual("Deep nested file content\n", str)
    }

    func testCopyResourceJSON() throws {
        let resourceURL: URL = try XCTUnwrap(Bundle.module.url(forResource: "data", withExtension: "json", subdirectory: "ResourcesCopy"))
        let data = try Data(contentsOf: resourceURL)
        let str = try String(contentsOf: resourceURL)
        XCTAssertTrue(str.contains("\"key\""), "JSON should contain key field")
        XCTAssertTrue(str.contains("42"), "JSON should contain number value")
        XCTAssertTrue(data.count > 0, "data.json should not be empty")
    }

    func testBundleInfo() throws {
        #if !SKIP
        // sadly, the Info.plist is auto-generated by SPM and cannot be overridden
        let _ = Bundle.module.infoDictionary ?? [:]
        let name = Bundle.module.bundleURL.deletingPathExtension().lastPathComponent
        XCTAssertTrue(name.hasSuffix("_SkipFoundationTests"), "unexpected name: \(name)")
        let moduleName = name.split(separator: "_").last?.description ?? name // turn "Skip_SkipFoundationTests" into "SkipFoundationTests"
        XCTAssertEqual("SkipFoundationTests", moduleName)

        //XCTAssertEqual(["BuildMachineOSBuild", "CFBundleDevelopmentRegion", "CFBundleIdentifier", "CFBundleInfoDictionaryVersion", "CFBundleName", "CFBundlePackageType", "CFBundleSupportedPlatforms", "DTCompiler", "DTPlatformBuild", "DTPlatformName", "DTPlatformVersion", "DTSDKBuild", "DTSDKName", "DTXcode", "DTXcodeBuild", "LSMinimumSystemVersion"], Set(info.keys))
        //XCTAssertEqual("Skip_SkipFoundationTests", info["CFBundleName"] as? String)
        #endif
    }

    func testMainBundleInfo() throws {
        let info = Bundle.main.infoDictionary
        if !isRobolectric {
            throw XCTSkip("testMainBundleInfo only checked for Robolectric")
        }

        XCTAssertEqual("skip.foundation.test", info?["CFBundleIdentifier"] as? String) // "com.apple.dt.xctest.tool"
        XCTAssertEqual("skip.foundation.test", info?["CFBundleName"] as? String) // "xctest"
        XCTAssertEqual("skip.foundation.test", info?["CFBundleDisplayName"] as? String)
        XCTAssertEqual("skip.foundation.test", info?["CFBundleExecutable"] as? String) // xctest

        XCTAssertEqual("0", info?["CFBundleVersion"] as? String) // 23196
        XCTAssertEqual("", info?["CFBundleShortVersionString"] as? String) // 16.0

        XCTAssertEqual("android", info?["DTPlatformName"] as? String) // macosx
        XCTAssertEqual("28", info?["DTPlatformVersion"] as? String) // 15.0
        XCTAssertEqual("28", info?["MinimumOSVersion"] as? String) // nil
        XCTAssertEqual("android28", info?["DTSDKName"] as? String) // macosx15.0.internal
        XCTAssertEqual("robolectric", info?["BuildMachineOSBuild"] as? String) // 22A380021
    }
}
